### ISSUE TITLE
Create a Readme 

### ISSUE THREAD

**Issue by Symbolk** [danielcalencar/ra-szz#1]
Hi, I found this tool in one TSE2020 paper, where it is used to mine defect-introducing changes, here is what the paper says:

> RA-SZZ ﬁrst leverages the git diff command to identify the lines that were changed by defectﬁxing changes. From the identiﬁed lines, RA-SZZ ﬁlters away blank/comment lines, lines involving format modiﬁcations (e.g., modiﬁcation of code indentation) and those involving refactoring modiﬁcations. Then, for the remaining lines, RA-SZZ traces back through the change history to identify the changes that introduce the lines, which are identiﬁed as defect-introducing changes. RA-SZZ leverages the annotation graph [29] to trace back through the change history. Annotation graph was proposed by Zimmermann et al. [29]. The graph traces the evolution of lines of code along the code change history. Using the annotation graph, RASZZ will not stop its search for defect introduction changes at changes that involve format modiﬁcations or refactoring modiﬁcations instead it can further trace back through the code history to identify the actual defect-introducing changes. In addition, another advantage of RA-SZZ is that for a code statement involving multiple lines, RA-SZZ can automatically combine the lines into one line. Hence, RASZZ ensures the completeness of the code lines that are analyzed in our study.

> Just-In-Time Defect Identiﬁcation and Localization: A Two-Phase Framework, TSE 2020 

I found this is particularly interesting and might be useful for other researchers, but this project seems to be non-standard. Could you create a readme that self-explains itself?

Anyway, thanks! @danielcalencar

**Comment by danielcalencar** [comment]
Hello @Symbolk ,

Sorry for the delay in my reply. I was enjoying some vacations. 

This repository here should actually be deprecated. Have a look at this one:
https://github.com/danielcalencar/raszzprime <- this is the latest implementation for RA-SZZ

Let me know if you have issues running that impl.
